"""Regression coverage for the operator-facing dictionary restore script."""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit
from uuid import uuid4

import asyncpg
import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
RESTORE_SCRIPT = REPO_ROOT / "infra" / "scripts" / "restore_dict_tables.ps1"
DICT_TABLES = ("dict_entries", "dict_lookup_targets", "dict_redirects")


def _database_url() -> str:
    if value := os.getenv("DATABASE_URL"):
        return value
    env_path = REPO_ROOT / "services" / "api" / ".env"
    if env_path.exists():
        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            if raw_line.strip().startswith("DATABASE_URL="):
                return raw_line.split("=", 1)[1].strip().strip('"').strip("'")
    return "postgresql://claread:claread_dev@127.0.0.1:5432/claread"


def _with_database(database_url: str, database: str) -> str:
    parsed = urlsplit(database_url)
    return urlunsplit(parsed._replace(path=f"/{database}"))


def test_restore_script_uses_one_transaction_for_destructive_steps() -> None:
    source = RESTORE_SCRIPT.read_text(encoding="utf-8")

    begin = source.index("BEGIN;")
    truncate = source.index("TRUNCATE dict_lookup_targets")
    include = source.index("\\ir ")
    sequence_repair = source.index("SELECT setval('dict_entries_id_seq'")
    commit = source.index("COMMIT;")

    assert begin < truncate < include < sequence_repair < commit


@pytest.mark.asyncio
async def test_restore_failure_after_truncate_preserves_existing_rows(tmp_path: Path) -> None:
    """Use disposable databases when the PostgreSQL CLI is available locally."""

    required = ("pg_dump", "pg_restore", "psql", "pwsh")
    if missing := [name for name in required if shutil.which(name) is None]:
        pytest.skip(f"local PostgreSQL restore tools unavailable: {', '.join(missing)}")

    admin_url = _database_url()
    source_database = f"dict_restore_source_{uuid4().hex}"
    target_database = f"dict_restore_target_{uuid4().hex}"
    source_url = _with_database(admin_url, source_database)
    target_url = _with_database(admin_url, target_database)
    admin = await asyncpg.connect(admin_url)
    source_conn: asyncpg.Connection | None = None
    target_conn: asyncpg.Connection | None = None

    try:
        await admin.execute(f'CREATE DATABASE "{source_database}"')
        await admin.execute(f'CREATE DATABASE "{target_database}"')
        source_conn = await asyncpg.connect(source_url)
        target_conn = await asyncpg.connect(target_url)

        for table in DICT_TABLES:
            table_sql = f"""
                CREATE TABLE {table} (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    payload text NOT NULL
                )
            """
            await source_conn.execute(table_sql)
            await target_conn.execute(table_sql)
            await source_conn.execute(f"INSERT INTO {table} (payload) VALUES ('new')")
            await target_conn.execute(f"INSERT INTO {table} (payload) VALUES ('old')")
        await target_conn.execute(
            "ALTER TABLE dict_entries ADD CONSTRAINT reject_new_payload CHECK (payload <> 'new')"
        )

        dump_path = tmp_path / "dictionary.dump"
        subprocess.run(
            [
                "pg_dump",
                f"--dbname={source_url}",
                "--format=custom",
                "--data-only",
                "--no-owner",
                "--no-privileges",
                *(f"--table={table}" for table in DICT_TABLES),
                f"--file={dump_path}",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        expected_sha256 = hashlib.sha256(dump_path.read_bytes()).hexdigest()

        result = subprocess.run(
            [
                "pwsh",
                "-NoProfile",
                "-File",
                str(RESTORE_SCRIPT),
                "-DatabaseUrl",
                target_url,
                "-DumpPath",
                str(dump_path),
                "-ExpectedSha256",
                expected_sha256,
            ],
            check=False,
            capture_output=True,
            text=True,
        )

        assert result.returncode != 0
        for table in DICT_TABLES:
            assert await target_conn.fetchval(f"SELECT payload FROM {table}") == "old"
            assert await target_conn.fetchval(f"SELECT last_value FROM {table}_id_seq") == 1
    finally:
        if source_conn is not None:
            await source_conn.close()
        if target_conn is not None:
            await target_conn.close()
        for database in (source_database, target_database):
            await admin.execute(
                "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                "WHERE datname = $1 AND pid <> pg_backend_pid()",
                database,
            )
            await admin.execute(f'DROP DATABASE IF EXISTS "{database}"')
        await admin.close()
