export const clareadTailwindPreset = {
  colors: {
    // Foundation (migrating toward semantic; kept as compatibility aliases)
    "web-canvas": "var(--web-canvas)",
    "reader-paper": "var(--reader-paper)",
    "reader-stage": "var(--reader-stage)",
    "reader-reading-ink": "var(--reader-reading-ink)",
    "reader-reading-ink-strong": "var(--reader-reading-ink-strong)",
    "reader-reading-muted": "var(--reader-reading-muted)",
    "reader-annotation-vocab-fill": "var(--reader-annotation-vocab-fill)",
    "reader-annotation-vocab-fill-strong": "var(--reader-annotation-vocab-fill-strong)",
    "reader-annotation-phrase-fill": "var(--reader-annotation-phrase-fill)",
    "reader-annotation-phrase-fill-strong": "var(--reader-annotation-phrase-fill-strong)",
    "reader-annotation-context-fill": "var(--reader-annotation-context-fill)",
    "reader-annotation-context-fill-strong": "var(--reader-annotation-context-fill-strong)",
    "reader-annotation-grammar-fill": "var(--reader-annotation-grammar-fill)",
    "reader-annotation-grammar-fill-strong": "var(--reader-annotation-grammar-fill-strong)",
    "reader-annotation-structure-fill": "var(--reader-annotation-structure-fill)",
    "reader-annotation-structure-fill-strong": "var(--reader-annotation-structure-fill-strong)",
    surface: "var(--surface)",
    "surface-warm": "var(--surface-warm)",
    "surface-raised": "var(--surface-raised)",
    ink: "var(--ink)",
    "ink-soft": "var(--ink-soft)",
    muted: "var(--muted)",
    subtle: "var(--subtle)",
    hairline: "var(--hairline)",
    "lens-blue": "var(--lens-blue)",
    "lens-blue-soft": "var(--lens-blue-soft)",
    "vocab-amber": "var(--vocab-amber)",
    "phrase-lavender": "var(--phrase-lavender)",
    "context-blue": "var(--context-blue)",
    "grammar-violet": "var(--grammar-violet)",
    "structure-green": "var(--structure-green)",
    "error-red": "var(--error-red)",

    // Web semantic tokens (canonical for new primitives + composed)
    "surface-canvas": "var(--surface-canvas)",
    "surface-stage": "var(--surface-stage)",
    "surface-overlay": "var(--surface-overlay)",
    "text-primary": "var(--text-primary)",
    "text-secondary": "var(--text-secondary)",
    "action-primary": "var(--action-primary)",
    "action-primary-foreground": "var(--action-primary-foreground)",
    "action-secondary": "var(--action-secondary)",
    "action-secondary-foreground": "var(--action-secondary-foreground)",
    // Note: --interactive-hover / --interactive-active /
    // --interactive-quiet-hover resolve to gradient or surface recipes that
    // do NOT work as Tailwind `bg-*` utilities. They remain as semantic
    // CSS variables for explicit `background-image` / `background`
    // declarations only and are intentionally NOT aliased through
    // `--color-*` in @theme.
    "border-subtle": "var(--border-subtle)",
    "border-strong": "var(--border-strong)",
    "focus-ring": "var(--focus-ring)",
    "feedback-success": "var(--feedback-success)",
    "feedback-success-soft": "var(--feedback-success-soft)",
    "feedback-warning": "var(--feedback-warning)",
    "feedback-warning-soft": "var(--feedback-warning-soft)",
    "feedback-error": "var(--feedback-error)",
    "feedback-error-foreground": "var(--feedback-error-foreground)",
  },
  radius: {
    "control-xs": "var(--cl-radius-control-xs)",
    "control-sm": "var(--cl-radius-control-sm)",
    "control-md": "var(--cl-radius-control-md)",
    "surface-sm": "var(--cl-radius-surface-sm)",
    "surface-md": "var(--cl-radius-surface-md)",
    note: "var(--cl-radius-note)",
    panel: "var(--cl-radius-panel)",
    sheet: "var(--cl-radius-sheet)",
  },
  shadow: {
    1: "var(--cl-shadow-1)",
    2: "var(--cl-shadow-2)",
    3: "var(--cl-shadow-3)",
  },
} as const;
