export const clareadTailwindPreset = {
  colors: {
    "web-canvas": "var(--web-canvas)",
    "reader-paper": "var(--reader-paper)",
    surface: "var(--surface)",
    "surface-warm": "var(--surface-warm)",
    "surface-raised": "var(--surface-raised)",
    ink: "var(--ink)",
    "ink-soft": "var(--ink-soft)",
    muted: "var(--muted)",
    subtle: "var(--subtle)",
    hairline: "var(--hairline)",
    "lens-blue": "var(--lens-blue)",
    "lens-blue-soft": "var(--lens-blue-soft)",
    "vocab-amber": "var(--vocab-amber)",
    "phrase-lavender": "var(--phrase-lavender)",
    "context-blue": "var(--context-blue)",
    "grammar-violet": "var(--grammar-violet)",
    "structure-green": "var(--structure-green)",
    "error-red": "var(--error-red)",
  },
  radius: {
    "control-xs": "var(--cl-radius-control-xs)",
    "control-sm": "var(--cl-radius-control-sm)",
    "control-md": "var(--cl-radius-control-md)",
    "surface-sm": "var(--cl-radius-surface-sm)",
    "surface-md": "var(--cl-radius-surface-md)",
    note: "var(--cl-radius-note)",
    panel: "var(--cl-radius-panel)",
    sheet: "var(--cl-radius-sheet)",
  },
  shadow: {
    1: "var(--cl-shadow-1)",
    2: "var(--cl-shadow-2)",
    3: "var(--cl-shadow-3)",
  },
} as const;
